//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string OrderID { get; set; }
        public long FoodID { get; set; }
        public long FoodCatID { get; set; }
        public long UserID { get; set; }
        public long PositionID { get; set; }
        public long SessionID { get; set; }
        public System.DateTime OrderTime { get; set; }
        public string Status { get; set; }
    
        public virtual FoodCategoryMaster FoodCategoryMaster { get; set; }
        public virtual FoodMaster FoodMaster { get; set; }
        public virtual PositionMaster PositionMaster { get; set; }
        public virtual SessionMaster SessionMaster { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
