//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public long PermissionID { get; set; }
        public string PermissionName { get; set; }
        public string PermissionDescription { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
