//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionMaster
    {
        public SessionMaster()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long SessionID { get; set; }
        public string SessionName { get; set; }
        public Nullable<int> SessionLevel { get; set; }
        public Nullable<long> SessionBelongto { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
