//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Roles = new HashSet<Role>();
        }
    
        public long ID { get; set; }
        public string Usercode { get; set; }
        public string Username { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public Nullable<long> PositionID { get; set; }
        public long ReportingTo { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual PositionMaster PositionMaster { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
