//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCategoryMaster
    {
        public FoodCategoryMaster()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long FoodCatID { get; set; }
        public string FoodCatName { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
