//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERestaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantInsightEntities : DbContext
    {
        public RestaurantInsightEntities()
            : base("name=RestaurantInsightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FoodCategoryMaster> FoodCategoryMasters { get; set; }
        public DbSet<FoodMaster> FoodMasters { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<OrgChart> OrgCharts { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<PositionMaster> PositionMasters { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SessionMaster> SessionMasters { get; set; }
        public DbSet<SessionStructure> SessionStructures { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
    }
}
